# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-linux.yaml

on: [push]

jobs:
  go-test-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest]
    name: "go test with OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Run go test
        run: go test -v -p 1 ./...
